Git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -17,13 +17,13 @@ fi
 
 
 ##### Unit tests
-# printf "\n"
-# printf "\e[33;1m%s\e[0m\n" 'Running unit tests'
-# /path/to/flutter/bin/flutter test
-# if [ $? -ne 0 ]; then
-#   printf "\e[31;1m%s\e[0m\n" 'Unit tests error'
-#   exit 1
-# fi
-#
-# printf "\e[33;1m%s\e[0m\n" 'Finished running unit tests'
+printf "\n"
+printf "\e[33;1m%s\e[0m\n" 'Running unit tests'
+/usr/local/opt/dart/libexec/bin/pub run test
+if [ $? -ne 0 ]; then
+ printf "\e[31;1m%s\e[0m\n" 'Unit tests error'
+ exit 1
+fi
+
+printf "\e[33;1m%s\e[0m\n" 'Finished running unit tests'
 
